steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/aterriza-application/aterriza:v4:$COMMIT_SHA', '.']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'  # Agrega esta línea para definir la variable

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/aterriza-application/aterriza:v4:$COMMIT_SHA']
    env:
      - 'COMMIT_SHA=$COMMIT_SHA'  # Asegúrate de definir la variable nuevamente aquí

