name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          version: 'latest'

      - name: Build Docker image
        run: |
          export COMMIT_SHA=$(git rev-parse HEAD)
          docker build -t aterriza:v4 .
          docker tag aterriza:v4 gcr.io/aterriza-application/aterriza:v4

      - name: Authenticate with Google Cloud
        run: gcloud auth configure-docker

      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/aterriza-application/aterriza:v4

      - name: Autenticar con Google Cloud
        run: echo "$GCLOUD_AUTH_KEY" | base64 --decode > /tmp/gcloud.json && gcloud auth activate-service-account --key-file=/tmp/gcloud.json

      - name: Subir imagen de Docker al Registro de Contenedores de Google
        run: docker push gcr.io/aterriza-application/aterriza:v4

