name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'

      - name: Build Docker image
        run: |
          export COMMIT_SHA=$(git rev-parse HEAD)
          docker build . -t gcr.io/aterriza-application/YOUR_IMAGE_NAME:$COMMIT_SHA

      - name: Authenticate with Google Cloud
        run: gcloud auth configure-docker

      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/YOUR_PROJECT_ID/YOUR_IMAGE_NAME:$COMMIT_SHA

